### ISSUE TITLE
Sentinel collections and Black Images in Timeseries

### ISSUE THREAD

**Issue by Assylnur** [allenai/satlas-super-resolution#11]
Hello,

I only have access to Sentinel-l2A data for my project and am interested in applying your model. So, can I use Sentinel-2A data as input for the model? 

Some of the images in my timeseries image are black:
![0TCI](https://github.com/allenai/satlas-super-resolution/assets/78303602/5b939e1c-671e-4e85-8c9a-f8fcb915b77a)
Will they impact the overall performance or require any special preprocessing?

Your insights on these issues would be greatly appreciated. 
Thank you for your time and assistance.

**Comment by piperwolters** [comment]
Hi, thank you for your interest in the project!

1) Rather than keeping the black images in your timeseries, I would recommend repeating the good images. Our pretrained models don't see many (if any) black images, so I don't think it would work well.
2) Our models are trained exclusively on L1C imagery. Regarding L2A imagery, I have not tried inputting L2A into our pretrained models. I imagine it wouldn't work super well, because of the very different preprocessing, but you could try. If you are able to, you could try fine-tuning the model on L2A imagery.

**Comment by Assylnur** [comment]
Hi,

Thank you for your informative response! I have a few follow-up questions to better understand how to proceed:

1) Could you advise on where I can find L1C imagery? 

2)  I attempted to use L2A data with your pretrained models but, as you said, the results were not optimal. 
input:
![input](https://github.com/allenai/satlas-super-resolution/assets/78303602/f4233b2b-b387-447c-bb5d-7109d48764f8)
Result:
![result](https://github.com/allenai/satlas-super-resolution/assets/78303602/6729855d-72f3-47fe-8886-5253d70dab66)


Could you provide any recommendations for the fine-tuning the model with L2A imagery?

Thank you once again for your support.

**Comment by piperwolters** [comment]
1) If you want to download Sentinel-2 L1C imagery from the source, see [here:](https://docs.sentinel-hub.com/api/latest/data/sentinel-2-l1c/). We have details on how to process raw imagery into the format our models expect [here](https://github.com/allenai/satlas-super-resolution#how-to-process-raw-sentinel-2-data).

2) To finetune our model on L2A imagery, you might try loading in pretrained weights (from [here](https://github.com/allenai/satlas-super-resolution#model-weights)) and then trying to train on your data. I'm not sure how well it will work, it will depend on how much imagery you have.

**Comment by piperwolters** [comment]
Sorry, I missed this! Could you send the super-res outputs that you're getting for this input?
