### ISSUE TITLE
inference on single image 

### ISSUE THREAD

**Issue by rose-jinyang** [allenai/satlas-super-resolution#45]
Hello
How are you?
Thanks for contributing to this project.
I am going to do super-resolution of an image (with RGB-3 channels)of which size is 320x320.

python -m ssr.infer -opt ssr/options/infer_example.yml

I used the following options in the "infer_example.yml":

name: infer_example
model_type: SSRESRGANModel
scale: 4
num_gpu: auto
manual_seed: 0

data_dir: images/320/

n_lr_images: 1

save_path: testing_infer/

network_g:
  type: SSR_RRDBNet
  num_in_ch: 3  # number of Sentinel2 images * 3 channels (RGB)
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32

path:
  pretrain_network_g: weights/esrgan_1S2.pth
  param_key_g: params_ema
  strict_load_g: true

The inference script worked but I'm not sure if the outputted images are normal.
original low-resolution image (320x320 pixels in size)
![image](https://github.com/user-attachments/assets/92e56ed1-8db4-4f61-a449-6552b83d1beb)

lr.png (32x32 pixels in size)
![image](https://github.com/user-attachments/assets/dfc450f9-011a-437e-bf6f-382015a43c9c)

sr.png (128x128 pixels in size)
![image](https://github.com/user-attachments/assets/94909c1c-5bf2-40ff-9faa-0d488871b0f1)

I want to get 4x upscaled image (1280x1280 pixels in size) from original image.

**Comment by piperwolters** [comment]
Hi, thanks for you interest in our work!

Few things:
- Looks like the modality of your low-res image is from google imagery? Our pretrained models will be expecting Sentinel-2.
- I am unable to open your images to get a closer look, but want to make sure your low-res data input is in the shape `[number_lr_images * 32, 32, 3]`?
- To get a super-resolved 1280x1280px image from the 320x320px image, I would l recommend chunking the 320x320 image into 32x32px chunks and feeding each chunk through inference individually, and then stitch these chunks together. This is because the model was trained on these small 32x32 chunks and might not do well with larger input.

**Comment by rose-jinyang** [comment]
Hi @piperwolters 
Thanks for your reply.
Yes. the original low quality image is from google maps.
its shape is 320x320x3.
So all the trained model in this repo were trained on 32x32 pixel size of images, Right?
if so, should I apply the model "esrgan_1S2.pth" for inference on each 32x32px size of image chunk?
If the original image size is 640x640px, should I run the model 20x20=400 times?

**Comment by lokeshsk** [comment]
Hi @rose-jinyang ,

As @piperwolters highlighted earlier, that the image size should be 32x32. Yes, as you guessed correctly that the model needs to run on each chunk of 32x32. 

However, for larger images you can use something like **gdal_retile** (https://gdal.org/en/latest/programs/gdal_retile.html) to tiles the large image into size of 32x32 and after applying you can try something like **gdal_merge** (https://gdal.org/en/latest/programs/gdal_merge.html). 


NOTE: gdal_merge might not work as expected as the images will lose all the geo-spatial information, once the set of images (LR) have been passed through the model, to make them SR.

**Comment by rose-jinyang** [comment]
Thank you @lokeshsk

**Comment by piperwolters** [comment]
Thanks @lokeshsk ! 

@rose-jinyang let me know if you have more questions.

**Comment by mourabitiziyad** [comment]
Hello! Thank you for this @piperwolters ! For images that cannot be divided to equal 32x32 chunks, would you recommend padding the input image? I tried that but I am not sure I have been expected results.

My input image (sentinel-2 image from Copernicus, TCI format) was 432 × 434, and I used gdalwarp to add padding to make it 448x448. so that gdal_retile can equally divide the image into 32x32 chunks. I then converted each chunk to png from tif so that the model (same config as @rose-jinyang on infer_example.yml) can take it.

Input:

![Image](https://github.com/user-attachments/assets/536b43e7-878e-487c-a742-f2b3cc765796)

Padded input:

![Image](https://github.com/user-attachments/assets/06256ff0-eb61-441e-9603-b98de118c661)

SR:

![Image](https://github.com/user-attachments/assets/612b7d64-ba44-40cf-bbe9-9802890b2068)


the above images are screenshots so you won't be able to carefully examine these. But I was wondering if these results are what would be expected or if I am doing something fundamentally wrong. Any feedback would help greatly!
