### ISSUE TITLE
Other spectral bands of Sentinel 2 (S2)

### ISSUE THREAD

**Issue by yerzhan7orazayev** [allenai/satlas-super-resolution#7]
Is there any possibility to SR not only RGB images from S2 rather other spectral bands, such as NIR?

Thanks.

**Comment by piperwolters** [comment]
We have not worked on super-resolving non-RGB bands, but it would certainly be doable in this codebase if you have a dataset of high-resolution imagery with NIR bands. You would just need to change the number of desired output channels, and maybe a few other hardcoded values.

**Comment by yerzhan7orazayev** [comment]
Thanks for your reply.
Unfortunately, I do not have dataset of high-resolution imagery for non-RGB bands. I was thinking that using your model directly on single channel input of non-RGB image will not give the desired output? If the problem is with number of channels, one can simply replicate up to three channels at input stage.

**Comment by piperwolters** [comment]
Yeah, because our model is just trained to go from Sentinel-2 (RGB or all bands) -> NAIP (RGB), it won't know how to produce super-resolved non-RGB bands. I'm not sure what the output would look like if you tried feeding in three channels of non-RGB to our pretrained models.
If you try it, please share the results!
